export const site = {
  name: "NRI to USA",
  domain: "www.nritousa.com",
  url: "https://www.nritousa.com",
  tagline: "The complete USA guide for NRIs and immigrants",
  description:
    "Practical guides for NRIs and immigrants in the USA covering finance, housing, cars, taxes, investing, retirement, India-USA money transfers, and real immigrant experiences.",
  /** Default author/publisher used in structured data across the site. */
  author: "NRI to USA Editorial Team",
  publisher: "NRI to USA",
  /** Legal owner of the website (shown in footer, About, and legal pages). */
  owner: "Wealth Building Academy LLC",
  /** Path to the dynamic default Open Graph image (generated by next/og). */
  ogImage: "/opengraph-image",
  email: "hello@nritousa.com",
  /** First year of publication — used in copyright and Organization schema. */
  foundingYear: 2026,
  /**
   * Social profiles. Empty until real accounts exist — we don't render links
   * to profiles that 404 (every previous handle did; see the audit). Re-add a
   * key here and the footer, contact page, and Organization `sameAs` light up
   * again automatically.
   */
  social: {} as Partial<
    Record<"twitter" | "instagram" | "youtube" | "linkedin", string>
  >,
};

export type Site = typeof site;
