export const site = {
  name: "NRI to USA",
  domain: "www.nritousa.com",
  url: "https://www.nritousa.com",
  tagline: "The complete USA guide for NRIs and immigrants",
  description:
    "Practical guides for NRIs and immigrants in the USA covering finance, housing, cars, taxes, investing, retirement, India-USA money transfers, and real immigrant experiences.",
  /** Default author/publisher used in structured data across the site. */
  author: "NRI to USA Editorial Team",
  publisher: "NRI to USA",
  /** Path to the dynamic default Open Graph image (generated by next/og). */
  ogImage: "/opengraph-image",
  email: "hello@nritousa.com",
  /** First year of publication — used in copyright and Organization schema. */
  foundingYear: 2026,
  social: {
    twitter: "https://twitter.com/nritousa",
    instagram: "https://instagram.com/nritousa",
    youtube: "https://youtube.com/@nritousa",
    linkedin: "https://linkedin.com/company/nritousa",
  },
  /** Twitter/X handle for the twitter:creator / twitter:site cards. */
  twitterHandle: "@nritousa",
};

export type Site = typeof site;
