export const site = {
  name: "NRI to USA",
  domain: "www.nritousa.com",
  url: "https://www.nritousa.com",
  tagline: "The complete USA guide for NRIs and immigrants",
  /**
   * Short positioning line used as the default social (OG/Twitter) description.
   * Kept separate from {description}: the long sentence is better for SEO,
   * this punchy line reads better in link previews and matches the OG image.
   */
  socialTagline: "Immigration • Tax • Wealth • Return to India Planning",
  description:
    "Practical guides for NRIs and immigrants in the USA covering finance, housing, cars, taxes, investing, retirement, India-USA money transfers, and real immigrant experiences.",
  /** Default author/publisher used in structured data across the site. */
  author: "NRI to USA Editorial Team",
  publisher: "NRI to USA",
  /** Legal owner of the website (shown in footer, About, and legal pages). */
  owner: "Wealth Building Academy LLC",
  /** Path to the dynamic default Open Graph image (generated by next/og). */
  ogImage: "/opengraph-image",
  email: "support@nritousa.com",
  /** State of incorporation for {owner}. Drives governing law in the policies. */
  state: "Illinois",
  /**
   * Public mailing address shown on the legal pages. Left as a placeholder
   * until the owner confirms an address they're comfortable publishing — see
   * docs/legal-policy-review-todos.md. Empty string hides the line.
   */
  mailingAddress: "",
  /**
   * Single source of truth for the "Last updated" date stamped on every legal
   * page (Terms, Privacy, Disclaimer, Cookie Policy). Bump this whenever any
   * policy changes so all four stay consistent.
   */
  legalUpdated: "June 23, 2026",
  /** First year of publication — used in copyright and Organization schema. */
  foundingYear: 2026,
  /**
   * Social profiles. Empty until real accounts exist — we don't render links
   * to profiles that 404 (every previous handle did; see the audit). Re-add a
   * key here and the footer, contact page, and Organization `sameAs` light up
   * again automatically.
   */
  social: {} as Partial<
    Record<"twitter" | "instagram" | "youtube" | "linkedin", string>
  >,
};

export type Site = typeof site;
