/**
 * Monthly visa-bulletin pages: /visa-bulletin/<month>-<year>.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THE ONE RULE: a month page exists only for a bulletin the State Department
 * has actually PUBLISHED. Forecasts live on the predictions pages, never here.
 * Adding a month to PUBLISHED_MONTHS below is what creates the page, and the
 * test asserts every entry has a real snapshot behind it — so a month cannot be
 * listed before its data exists.
 *
 * Publishing a new month: docs/seo/visa-bulletin-monthly-runbook.md
 * ─────────────────────────────────────────────────────────────────────────
 *
 * Data comes from the files that already back the rest of the site — one
 * fully-populated snapshot per bulletin month under data/visa-bulletin/
 * snapshots/, generated by scripts/build-visa-bulletin-data.mjs. No second
 * parser, no hand-maintained duplicate of the cutoffs.
 */

import index from "../../data/visa-bulletin/index.json";

/* Snapshot files are static imports so the pages stay statically generated. */
import s202604 from "../../data/visa-bulletin/snapshots/2026-04.json";
import s202605 from "../../data/visa-bulletin/snapshots/2026-05.json";
import s202606 from "../../data/visa-bulletin/snapshots/2026-06.json";
import s202607 from "../../data/visa-bulletin/snapshots/2026-07.json";
import s202608 from "../../data/visa-bulletin/snapshots/2026-08.json";
import s202609 from "../../data/visa-bulletin/snapshots/2026-09.json";

export type Cutoff = string; // ISO date, "C" (current) or "U" (unavailable)

export interface CountryCutoffs {
  fad: Cutoff;
  dff: Cutoff;
}
export type CategoryRow = Record<string, CountryCutoffs>;

export interface BulletinSnapshot {
  bulletinMonth: string;
  source: string;
  sourceLabel: string;
  categories: Record<string, CategoryRow>;
  family?: Record<string, CategoryRow>;
}

/**
 * Snapshots reachable from a month page. Only the recent window is imported —
 * a month page needs its own month plus the previous one to compute movement,
 * and the 24-bulletin chart reads history.json instead.
 */
const SNAPSHOTS: Record<string, BulletinSnapshot> = {
  "2026-04": s202604 as BulletinSnapshot,
  "2026-05": s202605 as BulletinSnapshot,
  "2026-06": s202606 as BulletinSnapshot,
  "2026-07": s202607 as BulletinSnapshot,
  "2026-08": s202608 as BulletinSnapshot,
  "2026-09": s202609 as BulletinSnapshot,
};

/**
 * Bulletin months that have a live page, newest first.
 *
 * ⚠️ Add a month ONLY after the State Department publishes that bulletin.
 * As of 2026-09-16 the latest published bulletin is September 2026; October
 * 2026 is the first FY-2027 bulletin and was not out yet.
 */
export const PUBLISHED_MONTHS: string[] = ["2026-09"];

export const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** "2026-09" → "september-2026" (the URL slug). */
export function monthSlug(bulletinMonth: string): string {
  const [y, m] = bulletinMonth.split("-");
  return `${MONTH_NAMES[Number(m) - 1].toLowerCase()}-${y}`;
}

/** "september-2026" → "2026-09", or null when the slug is not a month. */
export function slugToMonth(slug: string): string | null {
  const m = /^([a-z]+)-(\d{4})$/.exec(slug);
  if (!m) return null;
  const i = MONTH_NAMES.findIndex((n) => n.toLowerCase() === m[1]);
  if (i === -1) return null;
  return `${m[2]}-${String(i + 1).padStart(2, "0")}`;
}

/** "2026-09" → "September 2026". */
export function monthLabel(bulletinMonth: string): string {
  const [y, m] = bulletinMonth.split("-");
  return `${MONTH_NAMES[Number(m) - 1]} ${y}`;
}

/** The month before this one, as a bulletin-month string. */
export function previousMonth(bulletinMonth: string): string {
  const [y, m] = bulletinMonth.split("-").map(Number);
  const pm = m === 1 ? 12 : m - 1;
  const py = m === 1 ? y - 1 : y;
  return `${py}-${String(pm).padStart(2, "0")}`;
}

export function getSnapshot(bulletinMonth: string): BulletinSnapshot | null {
  return SNAPSHOTS[bulletinMonth] ?? null;
}

export function isPublishedMonth(bulletinMonth: string): boolean {
  return PUBLISHED_MONTHS.indexOf(bulletinMonth) !== -1;
}

/** Slugs with a live page, newest first — drives the hub index and the sitemap. */
export function publishedMonthSlugs(): string[] {
  return PUBLISHED_MONTHS.slice()
    .sort()
    .reverse()
    .map(monthSlug);
}

export const monthPath = (bulletinMonth: string) =>
  `/visa-bulletin/${monthSlug(bulletinMonth)}`;

/* ── Movement ───────────────────────────────────────────────────────────── */

export type MovementKind =
  | "advanced"
  | "retrogressed"
  | "unchanged"
  | "became-current"
  | "became-unavailable"
  | "left-unavailable"
  | "no-comparison";

export interface Movement {
  kind: MovementKind;
  /** Days the cutoff moved. Positive is forward. Zero when not comparable. */
  days: number;
  /** Human phrase: "advanced 6 weeks", "unchanged", "became unavailable". */
  label: string;
  from: Cutoff;
  to: Cutoff;
}

const SPECIAL = ["C", "U"];

function parseCutoff(value: Cutoff): number | null {
  if (!value || SPECIAL.indexOf(value) !== -1) return null;
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!m) return null;
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}

/**
 * Describes how a cutoff moved between two bulletins.
 *
 * "C" and "U" are states, not dates, so a transition into or out of them is
 * reported as a transition rather than as a number of days. Getting this wrong
 * is the classic silent bug on movement trackers: treating "U" as an old date
 * produces a confident "retrogressed 4,000 days".
 */
export function describeMovement(from: Cutoff, to: Cutoff): Movement {
  const base = { days: 0, from, to };

  if (!from || !to) return { ...base, kind: "no-comparison", label: "No comparison available" };
  if (from === to) {
    if (to === "C") return { ...base, kind: "unchanged", label: "Current — no backlog" };
    if (to === "U") return { ...base, kind: "unchanged", label: "Still unavailable" };
    return { ...base, kind: "unchanged", label: "No movement" };
  }
  if (to === "C") return { ...base, kind: "became-current", label: "Became current" };
  if (to === "U") return { ...base, kind: "became-unavailable", label: "Became unavailable" };
  if (from === "U") return { ...base, kind: "left-unavailable", label: "A cutoff date returned" };
  if (from === "C") return { ...base, kind: "retrogressed", label: "A cutoff date was imposed" };

  const a = parseCutoff(from);
  const b = parseCutoff(to);
  if (a === null || b === null) {
    return { ...base, kind: "no-comparison", label: "No comparison available" };
  }

  const days = Math.round((b - a) / 86_400_000);
  if (days === 0) return { ...base, kind: "unchanged", label: "No movement" };

  const abs = Math.abs(days);
  const amount =
    abs >= 60
      ? `${Math.round(abs / 30.44)} month${Math.round(abs / 30.44) === 1 ? "" : "s"}`
      : abs >= 14
        ? `${Math.round(abs / 7)} week${Math.round(abs / 7) === 1 ? "" : "s"}`
        : `${abs} day${abs === 1 ? "" : "s"}`;

  return {
    ...base,
    days,
    kind: days > 0 ? "advanced" : "retrogressed",
    label: `${days > 0 ? "Advanced" : "Retrogressed"} ${amount}`,
  };
}

export interface MovementRow {
  category: string;
  categoryLabel: string;
  country: string;
  countryLabel: string;
  fad: Movement;
  dff: Movement;
}

export const COUNTRY_ORDER = ["india", "china", "mexico", "philippines", "row"];
export const COUNTRY_LABELS: Record<string, string> = {
  india: "India",
  china: "China (mainland)",
  mexico: "Mexico",
  philippines: "Philippines",
  row: "All other countries",
};

export const EB_LABELS: Record<string, string> = {
  eb1: "EB-1",
  eb2: "EB-2",
  eb3: "EB-3",
  eb3Other: "EB-3 Other Workers",
  eb4: "EB-4",
  eb5: "EB-5 Unreserved",
};

export const FAMILY_LABELS: Record<string, string> = {
  f1: "F1",
  f2a: "F2A",
  f2b: "F2B",
  f3: "F3",
  f4: "F4",
};

/**
 * Month-over-month change for every category/country pair in one table
 * (employment or family). Pairs missing from either snapshot are skipped
 * rather than rendered as a movement from nothing.
 */
export function movementTable(
  bulletinMonth: string,
  table: "categories" | "family"
): MovementRow[] {
  const now = getSnapshot(bulletinMonth);
  const prev = getSnapshot(previousMonth(bulletinMonth));
  if (!now) return [];

  const nowRows = (table === "family" ? now.family : now.categories) ?? {};
  const prevRows = (prev ? (table === "family" ? prev.family : prev.categories) : {}) ?? {};
  const labels = table === "family" ? FAMILY_LABELS : EB_LABELS;

  const out: MovementRow[] = [];
  for (const category of Object.keys(nowRows)) {
    for (const country of COUNTRY_ORDER) {
      const nowCell = nowRows[category]?.[country];
      if (!nowCell) continue;
      const prevCell = prevRows[category]?.[country];
      out.push({
        category,
        categoryLabel: labels[category] ?? category,
        country,
        countryLabel: COUNTRY_LABELS[country] ?? country,
        fad: describeMovement(prevCell?.fad ?? "", nowCell.fad),
        dff: describeMovement(prevCell?.dff ?? "", nowCell.dff),
      });
    }
  }
  return out;
}

/** Employment categories in the order the bulletin prints them. */
export const EB_ORDER = ["eb1", "eb2", "eb3", "eb3Other", "eb4", "eb5"];

/** The India employment rows, which is what the answer-first block leads on. */
export function indiaEmploymentMovement(bulletinMonth: string): MovementRow[] {
  const order = EB_ORDER;
  return movementTable(bulletinMonth, "categories")
    .filter((r) => r.country === "india")
    .sort((a, b) => order.indexOf(a.category) - order.indexOf(b.category));
}

export const BULLETIN_ARCHIVE_URL: string = index.source;
